<?php

namespace EdgeWeb\Project\EmployeeBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLatestProjects()
	{
		return $this
            ->createQueryBuilder('p')
            ->select('p')
           // ->where('c.project LIKE :id')->setParameter('id', $project)
            ->orderBy('p.datecreated', 'DESC')
            ->getQuery()
            ->getResult()
        ;
	}
}