<?php

namespace EdgeWeb\Project\EmployeeBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
	public function getProjectName()
	{
		return $this
            ->createQueryBuilder('t')
            ->select('t.project')
            ->where('t.id = :id')->setParameter('id', $this->id)
           // ->orderBy('t.workingday', 'DESC')
            ->getQuery()
            ->getResult()
        ;
	}

    public function getTasksForProject($projectId)
    {
        $qb = $this->createQueryBuilder('t')
                   ->select('t')
                   ->where('t.project = :project_id')
                   ->addOrderBy('t.datecreated','DESC')
                   ->setParameter('project_id', $projectId);


        return $qb->getQuery()
                  ->getResult();
    }

    public function getTasksForUser($userName)
    {
        $qb = $this->createQueryBuilder('t')
                   ->select('t')
                   ->where('t.createdby = :user')
                   ->addOrderBy('t.datecreated','DESC')
                   ->setParameter('user', $userName);


        return $qb->getQuery()
                  ->getResult();
    }

}
