department:
    path:     /
    defaults: { _controller: "EmployeeBundle:Department:index" }

department_show:
    path:     /{id}/show
    defaults: { _controller: "EmployeeBundle:Department:show" }

department_new:
    path:     /new
    defaults: { _controller: "EmployeeBundle:Department:new" }

department_create:
    path:     /create
    defaults: { _controller: "EmployeeBundle:Department:create" }
    methods:  POST

department_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmployeeBundle:Department:edit" }

department_update:
    path:     /{id}/update
    defaults: { _controller: "EmployeeBundle:Department:update" }
    methods:  [POST, PUT]

department_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmployeeBundle:Department:delete" }
    methods:  [POST, DELETE]
