<?php

namespace EdgeWeb\Project\PaycomBundle\Repository;

/**
 * PayrollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayrollRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllPending()
	{
		return $this
            ->createQueryBuilder('p')
            ->select('p')
            ->where('p.status = :status')
            ->setParameter('status', 'pending')
            ->orderBy('p.date', 'DESC')
            ->getQuery()
            ->getResult()
        ;
	}

	public function findAllPaid()
	{
		return $this
            ->createQueryBuilder('p')
            ->select('p')
            ->where('p.status = :status')
            ->setParameter('status', 'paid')
            ->orderBy('p.date', 'DESC')
            ->getQuery()
            ->getResult()
        ;
	}
	public function getCreatedPayrollByEmployeeAndDate($from,$to,$user)
	{
		return $this
            ->createQueryBuilder('p')
            ->select('p')
            ->andWhere('p.dateFrom = :date_from')
            ->andWhere('p.dateTo = :date_to')
            ->andWhere('p.users = :user')
            ->setParameter('date_from', $from)
            ->setParameter('date_to', $to)
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
	}
}
