<?php

namespace EdgeWeb\Project\PaycomBundle\Repository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEmployeeRate($user)
	{
		return $this->createQueryBuilder('r')
			->select('r.hourlyRate')
            ->where('r.users = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
	}
}
